### PR TITLE
Rhas fix game engine const correctdness

### LINKED ISSUE #19: [Code Logic] Game engine
After the #18 Const Correctdness isuee, the game runs but no movement happens when the inputs are pressed. This needs to be dug, for the game to work with good code design

### PR DESCRIPTION
**Pull request by Itsukan0**
This PR makes the game run properly with all the features working as before, but with a proper codebase.
Closes #19

### CODE REVIEW

File: source/box_collider.h [hunk 1]
```diff
@@ -3,21 +3,21 @@
...
     ~BoxCollider();
-    bool overlaps(BoxCollider other);
-    int getPosX();
-    int getPosY();
-    int getHalfWidth();
-    int getHalfHeight();
+    bool overlaps(BoxCollider const other);
+    int getPosX() const;
+    int getPosY() const;
+    int getHalfWidth() const;
```
Comment (Woyanoro) [inline source/box_collider.h:17]:
```suggestion
    int getHalfWidth() const;
```

**Review by Woyanoro — APPROVED** [review]

File: source/inputs.h [hunk 2]
```diff
@@ -1,12 +1,13 @@
...
 #define INPUTS_H
 
-struct GLFWwindow;
 #include <queue>
 #include <unordered_set>
 
 #include <iostream>
 
+struct GLFWwindow;
+
```
Comment (Woyanoro) [inline source/inputs.h:10]: Is there a reason to move this struct declaration after includes?
